/* Add TWEEN.js for smooth camera animations */
/**
 * Tween.js - Licensed under the MIT license
 * https://github.com/tweenjs/tween.js
 */
(function(f,e){"undefined"!==typeof exports&&"undefined"!==typeof module?module.exports=e():"function"===typeof define&&define.amd?define(e):f.TWEEN=e()})(this,function(){var f=[];return{getAll:function(){return f},removeAll:function(){f=[]},add:function(e){f.push(e)},remove:function(e){e=f.indexOf(e);-1!==e&&f.splice(e,1)},update:function(e,g){if(0===f.length)return!1;e=void 0!==e?e:TWEEN.now();for(var d=0;d<f.length;)f[d].update(e)||g?d++:f.splice(d,1);return!0}};});
TWEEN.now="undefined"!==typeof window&&void 0!==window.performance&&void 0!==window.performance.now?function(){return window.performance.now()}:Date.now;
TWEEN.Tween=function(f){this._object=f;this._valuesStart={};this._valuesEnd={};this._valuesStartRepeat={};this._duration=1E3;this._repeat=0;this._repeatDelayTime=void 0;this._yoyo=!1;this._isPlaying=!1;this._reversed=!1;this._delayTime=0;this._startTime=null;this._easingFunction=TWEEN.Easing.Linear.None;this._interpolationFunction=TWEEN.Interpolation.Linear;this._chainedTweens=[];this._onStartCallback=null;this._onStartCallbackFired=!1;this._onUpdateCallback=null;this._onCompleteCallback=null;this._onStopCallback=
null;return this};
TWEEN.Tween.prototype={to:function(f,e){this._valuesEnd=f;void 0!==e&&(this._duration=e);return this},start:function(f){TWEEN.add(this);this._isPlaying=!0;this._onStartCallbackFired=!1;this._startTime=void 0!==f?"string"===typeof f?TWEEN.now()+parseFloat(f):f:TWEEN.now();this._startTime+=this._delayTime;for(var e in this._valuesEnd){if(this._valuesEnd[e]instanceof Array){if(0===this._valuesEnd[e].length)continue;this._valuesEnd[e]=[this._object[e]].concat(this._valuesEnd[e])}void 0!==this._object[e]&&
(this._valuesStart[e]=this._object[e],0===this._valuesStart[e]instanceof Array&&(this._valuesStart[e]*=1),this._valuesStartRepeat[e]=this._valuesStart[e]||0)}return this},stop:function(){if(!this._isPlaying)return this;TWEEN.remove(this);this._isPlaying=!1;null!==this._onStopCallback&&this._onStopCallback.call(this._object,this._object);this.stopChainedTweens();return this},end:function(){this.update(this._startTime+this._duration);return this},stopChainedTweens:function(){for(var f=0,e=this._chainedTweens.length;f<
e;f++)this._chainedTweens[f].stop()},delay:function(f){this._delayTime=f;return this},repeat:function(f){this._repeat=f;return this},repeatDelay:function(f){this._repeatDelayTime=f;return this},yoyo:function(f){this._yoyo=f;return this},easing:function(f){this._easingFunction=f;return this},interpolation:function(f){this._interpolationFunction=f;return this},chain:function(){this._chainedTweens=arguments;return this},onStart:function(f){this._onStartCallback=f;return this},onUpdate:function(f){this._onUpdateCallback=
f;return this},onComplete:function(f){this._onCompleteCallback=f;return this},onStop:function(f){this._onStopCallback=f;return this},update:function(f){var e;if(f<this._startTime)return!0;!1===this._onStartCallbackFired&&(null!==this._onStartCallback&&this._onStartCallback.call(this._object,this._object),this._onStartCallbackFired=!0);var d=(f-this._startTime)/this._duration;d=0===this._duration||1<d?1:d;var a=this._easingFunction(d);for(e in this._valuesEnd)if(void 0!==this._valuesStart[e]){var b=this._valuesStart[e]||
0,c=this._valuesEnd[e];c instanceof Array?this._object[e]=this._interpolationFunction(c,a):("string"===typeof c&&(c="+"===c.charAt(0)||"-"===c.charAt(0)?b+parseFloat(c):parseFloat(c)),"number"===typeof c&&(this._object[e]=b+(c-b)*a))}if(null!==this._onUpdateCallback&&this._onUpdateCallback.call(this._object,a),1===d)if(0<this._repeat){isFinite(this._repeat)&&this._repeat--;for(e in this._valuesStartRepeat)this._valuesStartRepeat[e]instanceof Array||"string"===typeof this._valuesEnd[e]||(this._valuesStartRepeat[e]=
this._valuesStartRepeat[e]+this._valuesEnd[e]-this._valuesStart[e]),this._valuesStart[e]=this._valuesStartRepeat[e];this._yoyo&&(a=this._reversed,this._reversed=!a);this._startTime=void 0!==this._repeatDelayTime?f+this._repeatDelayTime:f+this._delayTime}else{null!==this._onCompleteCallback&&this._onCompleteCallback.call(this._object,this._object);f=0;for(e=this._chainedTweens.length;f<e;f++)this._chainedTweens[f].start(this._startTime+this._duration);return!1}return!0}};
TWEEN.Easing={Linear:{None:function(f){return f}},Quadratic:{In:function(f){return f*f},Out:function(f){return f*(2-f)},InOut:function(f){return 1>(f*=2)?.5*f*f:-.5*(--f*(f-2)-1)}},Cubic:{In:function(f){return f*f*f},Out:function(f){return--f*f*f+1},InOut:function(f){return 1>(f*=2)?.5*f*f*f:.5*((f-=2)*f*f+2)}},Quartic:{In:function(f){return f*f*f*f},Out:function(f){return 1- --f*f*f*f},InOut:function(f){return 1>(f*=2)?.5*f*f*f*f:-.5*((f-=2)*f*f*f-2)}},Quintic:{In:function(f){return f*f*f*f*f},
Out:function(f){return--f*f*f*f*f+1},InOut:function(f){return 1>(f*=2)?.5*f*f*f*f*f:.5*((f-=2)*f*f*f*f+2)}},Sinusoidal:{In:function(f){return 1-Math.cos(f*Math.PI/2)},Out:function(f){return Math.sin(f*Math.PI/2)},InOut:function(f){return.5*(1-Math.cos(Math.PI*f))}},Exponential:{In:function(f){return 0===f?0:Math.pow(1024,f-1)},Out:function(f){return 1===f?1:1-Math.pow(2,-10*f)},InOut:function(f){return 0===f?0:1===f?1:1>(f*=2)?.5*Math.pow(1024,f-1):.5*(-Math.pow(2,-10*(f-1))+2)}},Circular:{In:function(f){return 1-
Math.sqrt(1-f*f)},Out:function(f){return Math.sqrt(1- --f*f)},InOut:function(f){return 1>(f*=2)?-.5*(Math.sqrt(1-f*f)-1):.5*(Math.sqrt(1-(f-=2)*f)+1)}},Elastic:{In:function(f){var e=.1;var d=.4;if(0===f)return 0;if(1===f)return 1;!d||1>d?(d=1,e=.1):e=.1*Math.asin(1/d)/(2*Math.PI);return-(d*Math.pow(2,10*(f-=1))*Math.sin(2*(f-e)*Math.PI/.4))},Out:function(f){var e=.1;var d=.4;if(0===f)return 0;if(1===f)return 1;!d||1>d?(d=1,e=.1):e=.1*Math.asin(1/d)/(2*Math.PI);return d*Math.pow(2,-10*f)*Math.sin(2*
(f-e)*Math.PI/.4)+1},InOut:function(f){var e=.1;var d=.4;if(0===f)return 0;if(1===f)return 1;!d||1>d?(d=1,e=.1):e=.1*Math.asin(1/d)/(2*Math.PI);return 1>(f*=2)?-.5*d*Math.pow(2,10*(f-=1))*Math.sin(2*(f-e)*Math.PI/.4):.5*d*Math.pow(2,-10*(f-=1))*Math.sin(2*(f-e)*Math.PI/.4)+1}},Back:{In:function(f){return f*f*(2.70158*f-1.70158)},Out:function(f){return--f*f*(2.70158*f+1.70158)+1},InOut:function(f){return 1>(f*=2)?.5*f*f*(3.5949095*f-2.5949095):.5*((f-=2)*f*(3.5949095*f+2.5949095)+2)}},Bounce:{In:function(f){return 1-
TWEEN.Easing.Bounce.Out(1-f)},Out:function(f){return f<1/2.75?7.5625*f*f:f<2/2.75?7.5625*(f-=1.5/2.75)*f+.75:f<2.5/2.75?7.5625*(f-=2.25/2.75)*f+.9375:7.5625*(f-=2.625/2.75)*f+.984375},InOut:function(f){return.5>f?.5*TWEEN.Easing.Bounce.In(2*f):.5*TWEEN.Easing.Bounce.Out(2*f-1)+.5}}};
TWEEN.Interpolation={Linear:function(f,e){var d=f.length-1,a=d*e,b=Math.floor(a),c=TWEEN.Interpolation.Utils.Linear;return 0>e?c(f[0],f[1],a):1<e?c(f[d],f[d-1],d-a):c(f[b],f[b+1>d?d:b+1],a-b)},Bezier:function(f,e){for(var d=0,a=f.length-1,b=Math.pow,c=TWEEN.Interpolation.Utils.Bernstein,k=0;k<=a;k++)d+=b(1-e,a-k)*b(e,k)*f[k]*c(a,k);return d},CatmullRom:function(f,e){var d=f.length-1,a=d*e,b=Math.floor(a),c=TWEEN.Interpolation.Utils.CatmullRom;return f[0]===f[d]?(0>e&&(b=Math.floor(a=d*(1+e))),c(f[(b-
1+d)%d],f[b],f[(b+1)%d],f[(b+2)%d],a-b)):0>e?f[0]-(c(f[0],f[0],f[1],f[1],-a)-f[0]):1<e?f[d]-(c(f[d],f[d],f[d-1],f[d-1],a-d)-f[d]):c(f[b?b-1:0],f[b],f[d<b+1?d:b+1],f[d<b+2?d:b+2],a-b)},Utils:{Linear:function(f,e,d){return(e-f)*d+f},Bernstein:function(f,e){var d=TWEEN.Interpolation.Utils.Factorial;return d(f)/d(e)/d(f-e)},Factorial:function(){var f=[1];return function(e){var d=1;if(f[e])return f[e];for(var a=e;1<a;a--)d*=a;return f[e]=d}}(),CatmullRom:function(f,e,d,a,b){f=.5*(d-f);a=.5*(a-e);var c=
b*b;return(2*e-2*d+f+a)*b*c+(-3*e+3*d-2*f-a)*c+f*b+e}}};
